### ISSUE TITLE
Support indieauth protocol

### ISSUE THREAD

**Issue by cweiske** [fkooman/indiecert#1]
I'd be nice to make indiecert play as indieauth server.

Details can be found at https://indiewebcamp.com/distributed-indieauth

**Comment by fkooman** [comment]
Hi,

I wrote a small proposal to update the IndieAuth protocol to allow for compatibility. They are only minor changes that make sense regardless of the existence of IndieCert.

https://www.tuxed.net/fkooman/blog/proposed_changes_to_indieauth_protocol.html

**Comment by fkooman** [comment]
Some comments from Aaron: https://aaronparecki.com/articles/2015/03/05/1/re-proposed-changes-to-indieauth-protocol

**Comment by fkooman** [comment]
commit a87fdce3f1172e64cad2b8ad2dd029a428273837 and c7590d73264318f4734adb4c94f01337c89aeaf9 take care of `auth` endpoint and content type of code verification.

**Comment by fkooman** [comment]
I think I implemented all changes to make IndieCert compatible with IndieAuth!
