### ISSUE TITLE
implicit-grant flow for HTML5 clients (e.g. micropub)

### ISSUE THREAD

**Issue by elf-pavlik** [fkooman/indiecert#18]
similar to one used in https://unhosted.org | https://remotestorage.io/
* http://tools.ietf.org/html/draft-dejong-remotestorage-04#section-10

@aaronpk do you think it will also work with [SoLiD HTML5 apps](https://github.com/linkeddata/SoLiD#applications)? While most micropub clients nowadays run on remote machines as 'sever side' apps, some could also run on local devices as 'client side' apps...
@michielbdejong @melvincarvalho

**Comment by fkooman** [comment]
See also https://tools.ietf.org/html/rfc6749#section-4.2.

**Comment by aaronpk** [comment]
It's also possible to do the auth code flow from a browser, you don't actually need the implicit grant. The only reason traditional OAuth 2 servers don't recommend auth code flow for browsers is if they require the client_secret to do that request. But since there is no client_secret in IndieAuth, it's fine to use it from a browser.

**Comment by aaronpk** [comment]
Here's the section in the OAuth 2 spec about this: http://tools.ietf.org/html/rfc6749#section-4.1.3 Note that it doesn't even list the client_secret parameter.

**Comment by fkooman** [comment]
Hm...the same applied already to "native applications" as well. They can either use the authorization code or implicit grant flow. See https://tools.ietf.org/html/rfc6749#section-9.  I never thought about using 'authorization code' flow for HTML5 apps though, clever :) 

It may have some implications for CORS headers and such as JS will need to perform an AJAX request to the token endpoint to exchange the code for an access token.

**Comment by elf-pavlik** [comment]
looks also relevant: https://developers.google.com/identity/protocols/OAuth2UserAgent

**Comment by elf-pavlik** [comment]
rough implementation of code flow in HTML5 app (in a browser) available in https://github.com/elf-pavlik/unmpc/tree/indieauth
