### ISSUE TITLE
validate https:// using HTML5 form validation

### ISSUE THREAD

**Issue by elf-pavlik** [fkooman/indiecert#5]
http://www.html5rocks.com/en/tutorials/forms/html5forms/

**Comment by fkooman** [comment]
I think this will be too ugly to implement. And also confusing, i.e. a hostname (possibly with path) is accepted, so is a `https://` URL, but not `http://`. The easiest to implement is just to not accept anything that starts with `http://` and accept the rest initially. The server will validate it further... 

Does this even help? Most browsers don't really suggest what is wrong if you don't match a pattern...

**Comment by fkooman** [comment]
fixed it now by showing `https://` in front of the input box, and also requiring someone to enter something. So if you paste `https://tuxed.net` it will still work, if you paste `http://tuxed.net` it will fail.
